/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VENTANAS;

import CLASES.Usuarios;
import java.awt.Color;
import java.util.ArrayList;

/**
 *
 * @author HP
 */
public class LoginUsuario extends javax.swing.JFrame {

    /**
     * Creates new form LoginUsuario
     */
    public LoginUsuario() {
        initComponents();
        setSize(780, 600);
    }


    public void validar() {
        
        String contraseña_usuario = "Edumaster10";
        String Correo_Usuario = "dayamineral53@gmail.com";

        //USUARIO
        if (usuario.getText().isEmpty()) {
            requerido3.setText("*");
            requerido3.setForeground(Color.RED);

        } else if (!usuario.getText().equals(Correo_Usuario)){
                requerido3.setText("*");
            requerido3.setForeground(Color.RED);

        } else {
            requerido3.setText("✔");
            requerido3.setForeground(Color.GREEN);

        }

        //PASSWORD
        if (password_login.getText().isEmpty()) {
            requerido2.setText("*");
            requerido3.setForeground(Color.RED);

        } else if (!password_login.getText().equals(contraseña_usuario)) {
            requerido2.setText("*");
            requerido2.setForeground(Color.RED);

        } else {
            requerido2.setText("✔");
            requerido2.setForeground(Color.GREEN);

        }

        if (usuario.getText().isEmpty()
                || password_login.getText().isEmpty()
                || requerido2.getText().equals("*")
                || requerido3.getText().equals("*")) {
            iniciarsesion.setEnabled(false);
        } else {
            iniciarsesion.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel9 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        password_login = new javax.swing.JPasswordField();
        iniciarsesion = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        requerido2 = new javax.swing.JLabel();
        requerido3 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        requerido1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "LOGIN USUARIOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Copperplate Gothic Light", 1, 18), new java.awt.Color(14, 90, 123))); // NOI18N
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/perfil-del-usuario (3).png"))); // NOI18N
        jPanel7.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 270, 260));

        jLabel20.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N
        jLabel20.setText("USUARIO : ");
        jPanel7.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 282, 85, -1));

        usuario.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        usuario.setBorder(null);
        usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                usuarioKeyReleased(evt);
            }
        });
        jPanel7.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 170, -1));

        jLabel21.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N
        jLabel21.setText("CONTRASEÑA : ");
        jPanel7.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, -1, -1));

        password_login.setBorder(null);
        password_login.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                password_loginKeyReleased(evt);
            }
        });
        jPanel7.add(password_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 170, -1));

        iniciarsesion.setBackground(new java.awt.Color(255, 255, 255));
        iniciarsesion.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N
        iniciarsesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/ingresar (2).png"))); // NOI18N
        iniciarsesion.setText("INICIAR SESIÓN ");
        iniciarsesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarsesionActionPerformed(evt);
            }
        });
        jPanel7.add(iniciarsesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 441, -1, -1));

        jButton14.setBackground(new java.awt.Color(255, 255, 255));
        jButton14.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N
        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/anadir-amigo.png"))); // NOI18N
        jButton14.setText("REGISTRARSE");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 441, -1, -1));
        jPanel7.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, -1, 0));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel7.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 190, -1));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel7.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, 190, 10));

        requerido2.setFont(new java.awt.Font("Copperplate", 1, 13)); // NOI18N
        requerido2.setForeground(new java.awt.Color(255, 0, 0));
        jPanel7.add(requerido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, 80, 20));

        requerido3.setFont(new java.awt.Font("Copperplate", 1, 13)); // NOI18N
        requerido3.setForeground(new java.awt.Color(255, 0, 0));
        jPanel7.add(requerido3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 80, 20));

        jPanel9.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 430, 500));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/fond.jpg"))); // NOI18N
        jPanel9.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 780, 560));

        requerido1.setFont(new java.awt.Font("Copperplate", 1, 13)); // NOI18N
        requerido1.setForeground(new java.awt.Color(255, 0, 0));
        jPanel9.add(requerido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, 80, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarsesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarsesionActionPerformed

        this.dispose();
        MenuPrincipal vsar200 = new MenuPrincipal();
        vsar200.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_iniciarsesionActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void usuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usuarioKeyReleased
        validar();        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioKeyReleased

    private void password_loginKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_password_loginKeyReleased
        validar();        // TODO add your handling code here:
    }//GEN-LAST:event_password_loginKeyReleased

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton iniciarsesion;
    private javax.swing.JButton jButton14;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPasswordField password_login;
    private javax.swing.JLabel requerido1;
    private javax.swing.JLabel requerido2;
    private javax.swing.JLabel requerido3;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
