/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VENTANAS;

import java.awt.Color;

/**
 *
 * @author LENOVO
 */
public class Modificar_Direccion extends javax.swing.JFrame {

    /**
     * Creates new form Modificar_Direccion
     */
    public Modificar_Direccion() {
        initComponents();
                registrar_dire.setEnabled(false);

    }
    
     public void validar() {
       
        //IDPARRO

        if (id_parro.getText().isEmpty()) {
            requerido1.setText("*");
            requerido1.setForeground(Color.RED);

        } else {
            requerido1.setText("✔");
            requerido1.setForeground(Color.GREEN);

        }

        //PRINCIPAL
        if (principal_dire.getText().isEmpty()) {
            requerido2.setText("*");
            requerido2.setForeground(Color.RED);

        } else if (!principal_dire.getText().matches("[[A-Za-z]\\s]*{3,30}")) {
            requerido2.setText("*");
            requerido2.setForeground(Color.RED);

        } else {
            requerido2.setText("✔");
            requerido2.setForeground(Color.GREEN);

        }

        //SECUNDARIA
        if (secu_dire.getText().isEmpty()) {
            requerido3.setText("*");
            requerido3.setForeground(Color.RED);

        } else if (!secu_dire.getText().matches("[[A-Za-z]\\s]*{3,30}")) {
            requerido3.setText("*");
            requerido3.setForeground(Color.RED);

        } else {
            requerido3.setText("✔");
            requerido3.setForeground(Color.GREEN);

        }

        if (
                id_parro.getText().isEmpty()
                || principal_dire.getText().isEmpty()
                || secu_dire.getText().isEmpty()
                || requerido1.getText().equals("*")
                || requerido2.getText().equals("*")
                || id_parro.getText().isEmpty()
                || requerido3.getText().equals("*")) {
            registrar_dire.setEnabled(false);
        } else {
            registrar_dire.setEnabled(true);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        registrar_dire = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        id_parro = new javax.swing.JTextField();
        principal_dire = new javax.swing.JTextField();
        secu_dire = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        requerido1 = new javax.swing.JLabel();
        requerido2 = new javax.swing.JLabel();
        requerido3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MODIFCAR DIRECCION", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Copperplate Gothic Bold", 1, 24))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        jLabel1.setText("ID DIRECCION");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 85, -1, -1));

        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        jLabel2.setText("ID PARROQUIA");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, -1, -1));

        jLabel3.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        jLabel3.setText("CALLE PRINCIPAL");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, -1, -1));

        jLabel4.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        jLabel4.setText("CALLE SECUNDARIA");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, -1, -1));

        registrar_dire.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/disquete.png"))); // NOI18N
        registrar_dire.setText("GUARDAR");
        jPanel1.add(registrar_dire, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 425, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 82, 114, -1));

        id_parro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                id_parroKeyReleased(evt);
            }
        });
        jPanel1.add(id_parro, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 153, 114, -1));

        principal_dire.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                principal_direKeyReleased(evt);
            }
        });
        jPanel1.add(principal_dire, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 247, 122, -1));

        secu_dire.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                secu_direKeyReleased(evt);
            }
        });
        jPanel1.add(secu_dire, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 328, 122, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/direccion-de-casa.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 96, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/lupa (1).png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(631, 82, -1, -1));

        requerido1.setFont(new java.awt.Font("Copperplate", 1, 13)); // NOI18N
        requerido1.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(requerido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 150, 80, 20));

        requerido2.setFont(new java.awt.Font("Copperplate", 1, 13)); // NOI18N
        requerido2.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(requerido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 250, 80, 20));

        requerido3.setFont(new java.awt.Font("Copperplate", 1, 13)); // NOI18N
        requerido3.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(requerido3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 330, 80, 20));

        jButton3.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/izquierda.png"))); // NOI18N
        jButton3.setText("Regresar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 420, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 824, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void id_parroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_id_parroKeyReleased
validar();        // TODO add your handling code here:
    }//GEN-LAST:event_id_parroKeyReleased

    private void principal_direKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_principal_direKeyReleased
validar();        // TODO add your handling code here:
    }//GEN-LAST:event_principal_direKeyReleased

    private void secu_direKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_secu_direKeyReleased
validar();        // TODO add your handling code here:
    }//GEN-LAST:event_secu_direKeyReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
        MenuPrincipal vsar100= new MenuPrincipal();
        vsar100.setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField id_parro;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField principal_dire;
    private javax.swing.JButton registrar_dire;
    private javax.swing.JLabel requerido1;
    private javax.swing.JLabel requerido2;
    private javax.swing.JLabel requerido3;
    private javax.swing.JTextField secu_dire;
    // End of variables declaration//GEN-END:variables
}
