/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VENTANAS;

/**
 *
 * @author EDU
 */
public class Modificar_parroquia extends javax.swing.JFrame {

    /**
     * Creates new form Modificar_parroquia
     */
    public Modificar_parroquia() {
        initComponents();
        
        modificar_parroquia.setEnabled(false);
    }
    
    public void validar(){
        
         if(id_parroquia.getText().isEmpty()){
            requerido.setText("*Campo Obligatorio");
        }else{
            requerido.setText("");
        }
         
        if(nombre_parroquia.getText().isEmpty()){
            requerido.setText("*Campo Obligatorio");
            
        }else if(!nombre_parroquia.getText().matches("[[A-Za-z]\\s]*{3,30}")){
            requerido1.setText("Dato no valido");

        }else
        {
            requerido1.setText("");
        }

         
         if(id_parroquia.getText().isEmpty() || nombre_parroquia.getText().isEmpty() 
                 || nombre_parroquia.getText().equals("Dato no valido")){
            modificar_parroquia.setEnabled(false);
        }else{
            modificar_parroquia.setEnabled(true);
        }
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        id_parroquia = new javax.swing.JTextField();
        nombre_parroquia = new javax.swing.JTextField();
        codigo_postal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        requerido = new javax.swing.JLabel();
        modificar_parroquia = new javax.swing.JButton();
        requerido1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MODIFICAR PARROQUIA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Copperplate", 1, 24))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("ID Parroquia:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 62, -1, -1));

        jLabel3.setText("Nombre de la parroquia:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 104, -1, -1));

        jLabel4.setText("Codigo postal:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 146, -1, -1));

        id_parroquia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                id_parroquiaKeyReleased(evt);
            }
        });
        jPanel2.add(id_parroquia, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 54, 90, -1));

        nombre_parroquia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nombre_parroquiaKeyReleased(evt);
            }
        });
        jPanel2.add(nombre_parroquia, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 96, 90, -1));
        jPanel2.add(codigo_postal, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 90, -1));

        jLabel7.setText("Ingrese por favor el ID del equipo a modificar:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 34, -1, -1));

        jButton2.setBackground(new java.awt.Color(153, 153, 153));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/lupa (1).png"))); // NOI18N
        jButton2.setBorder(null);
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 30, 30));

        requerido.setFont(new java.awt.Font("Copperplate", 1, 13)); // NOI18N
        requerido.setForeground(new java.awt.Color(255, 0, 0));
        jPanel2.add(requerido, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, 180, 20));

        modificar_parroquia.setText("MODIFICAR");
        jPanel2.add(modificar_parroquia, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, -1, -1));

        requerido1.setFont(new java.awt.Font("Copperplate", 1, 13)); // NOI18N
        requerido1.setForeground(new java.awt.Color(255, 0, 0));
        jPanel2.add(requerido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, 180, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 575, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombre_parroquiaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombre_parroquiaKeyReleased
validar();        // TODO add your handling code here:
    }//GEN-LAST:event_nombre_parroquiaKeyReleased

    private void id_parroquiaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_id_parroquiaKeyReleased
validar();        // TODO add your handling code here:
    }//GEN-LAST:event_id_parroquiaKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modificar_parroquia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modificar_parroquia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modificar_parroquia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modificar_parroquia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modificar_parroquia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField codigo_postal;
    private javax.swing.JTextField id_parroquia;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton modificar_parroquia;
    private javax.swing.JTextField nombre_parroquia;
    private javax.swing.JLabel requerido;
    private javax.swing.JLabel requerido1;
    // End of variables declaration//GEN-END:variables
}
