/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VENTANAS;

import java.awt.Color;

/**
 *
 * @author HP
 */
public class Registro_Nacionaliad extends javax.swing.JFrame {

    /**
     * Creates new form Registro_Nacionaliad
     */
    public Registro_Nacionaliad() {
        initComponents();
        registrar_nacionalidad.setEnabled(false);
    }

    public void validar(){
        
        //ID NACIONALIDAD
        if (id_nacionalidad.getText().isEmpty()) {
            requerido1.setText("*");
            requerido1.setForeground(Color.RED);

        } else if (!id_nacionalidad.getText().matches("[[A-Z]{2}]*+\\-[[\\d]{4}]*")) {
            requerido1.setText("*");
            requerido1.setForeground(Color.RED);

        } else {
            requerido1.setText("✔");
            requerido1.setForeground(Color.GREEN);

        }
        
        //ID NACIONALIDAD
        if (nombre_nacionalidad.getText().isEmpty()) {
            requerido2.setText("*");
            requerido2.setForeground(Color.RED);

        } else if (!nombre_nacionalidad.getText().matches("[[A-Za-z]\\s]*{3,30}")) {
            requerido2.setText("*");
            requerido2.setForeground(Color.RED);

        } else {
            requerido2.setText("✔");
            requerido2.setForeground(Color.GREEN);

        }
        
        if (id_nacionalidad.getText().isEmpty()
                || nombre_nacionalidad.getText().isEmpty()
                || requerido1.getText().equals("*")
                || requerido2.getText().equals("*")){
            registrar_nacionalidad.setEnabled(false);
        } else {
            registrar_nacionalidad.setEnabled(true);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        id_nacionalidad = new javax.swing.JTextField();
        nombre_nacionalidad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        registrar_nacionalidad = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        requerido1 = new javax.swing.JLabel();
        requerido2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "REGISTRO NACIONALIDAD", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Copperplate Gothic Light", 1, 24))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        id_nacionalidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                id_nacionalidadKeyReleased(evt);
            }
        });
        jPanel1.add(id_nacionalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 156, -1));

        nombre_nacionalidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nombre_nacionalidadKeyReleased(evt);
            }
        });
        jPanel1.add(nombre_nacionalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 156, -1));

        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N
        jLabel2.setText("ID NACIONALIDAD : ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N
        jLabel3.setText("NOMBRE NACIONALIDAD : ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, -1, -1));

        registrar_nacionalidad.setBackground(new java.awt.Color(255, 255, 255));
        registrar_nacionalidad.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N
        registrar_nacionalidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/disquete.png"))); // NOI18N
        registrar_nacionalidad.setText("REGISTRAR");
        jPanel1.add(registrar_nacionalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/izquierda.png"))); // NOI18N
        jButton2.setText("REGRESAR ");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, -1, -1));

        requerido1.setFont(new java.awt.Font("Copperplate", 1, 13)); // NOI18N
        requerido1.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(requerido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, 80, 20));

        requerido2.setFont(new java.awt.Font("Copperplate", 1, 13)); // NOI18N
        requerido2.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(requerido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, 80, 20));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/ciudadania1.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void id_nacionalidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_id_nacionalidadKeyReleased
validar();
// TODO add your handling code here:
    }//GEN-LAST:event_id_nacionalidadKeyReleased

    private void nombre_nacionalidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombre_nacionalidadKeyReleased
validar();        // TODO add your handling code here:
    }//GEN-LAST:event_nombre_nacionalidadKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro_Nacionaliad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro_Nacionaliad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro_Nacionaliad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro_Nacionaliad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro_Nacionaliad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField id_nacionalidad;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nombre_nacionalidad;
    private javax.swing.JButton registrar_nacionalidad;
    private javax.swing.JLabel requerido1;
    private javax.swing.JLabel requerido2;
    // End of variables declaration//GEN-END:variables
}
